### ISSUE TITLE
Dylib being loaded on Windows instead of DLL

### ISSUE THREAD

**Issue by alexcu** [splashkit/splashkit-windows#1]
If we try running a fresh installation (as tested) on a new Windows VM for python3, the `dylib` extension is referenced to be loaded, instead of the `dll`.

Still compiled into the latest release, as per:

https://github.com/splashkit/splashkit-windows/blob/0d80d31676f7adb6132db300cb18fda01fd805dc/commands/python3/splashkit.py#L4

https://github.com/splashkit/splashkit-windows/blob/0d80d31676f7adb6132db300cb18fda01fd805dc/commands/python3/splashkit.py#L5

Would fix, but not sure what the process was to package new distributions into `splashkit-windows`...

**Comment by jakerenzella** [comment]
If there's a rush, you could put through the fix in a PR and then I can rebuild the Windows release + push it out? Otherwise I'll get around to this 👍

**Comment by alexcu** [comment]
Following code added to `splashkit.py` should resolve the issue, but I don't know how this needs to be released in Mac, Windows and Linux releases. I can manually merge this in for now.

**Comment by alexcu** [comment]
Resolved in https://github.com/splashkit/splashkit-windows/commit/2ad4a05d456595d1bac5d4f63fd8336e282bd758
